BE/.pnp.cjs
BE/package.json
BE/src/app.module.ts
BE/src/auth/auth.controller.spec.ts
BE/src/auth/auth.controller.ts
BE/src/auth/auth.module.ts
BE/src/auth/auth.service.spec.ts
BE/src/auth/auth.service.ts
BE/src/board/board.controller.spec.ts
BE/src/board/board.controller.ts
BE/src/board/board.module.ts
BE/src/board/board.service.spec.ts
BE/src/board/board.service.ts
BE/yarn.lock

- nest g resource 명령 이용
- board 모듈, 컨트롤러, 서비스 파일 생성
- auth 모듈, 컨트롤러, 서비스 파일 생성

✨ [BE] generated resource of board and auth

---

BE/.gitignore
BE/.pnp.cjs
BE/package.json
BE/src/app.module.ts
BE/src/auth/auth.module.ts
BE/src/auth/entities/user.entity.ts
BE/src/board/board.module.ts
BE/src/board/entities/board.entity.ts
BE/src/config/typeorm.config.ts
BE/tsconfig.json
BE/yarn.lock

- TypeORM 설정파일 추가
- app module에 typeorm import
- user entity 구현
- auth 모듈에 user entity 등록
- board entity 구현
- board 모듈에 board entity 등록

✨ [BE] MySQL 연결 설정, User 및 Board Entity 구현

---

packages/client/index.html
packages/client/src/App.tsx
packages/client/src/Router.tsx
packages/client/src/main.tsx

close #86 
- main.tsx -> App.tsx 이름 변경
- App.tsx -> Router.tsx 이름 변경
- 기존의 HashRouter를 사용하던 방식을 createBrowserRouter를 사용하는 방식으로 변경 
- createBrowserRouter가 더 최신의 방식
- createBrowserRouter 사용 시 페이지별 접근 제한이 더 쉬움
- 더 많은 데이터 API 사용 가능
- Router.tsx 부분
- 멘토링 내용 반영

[FE] [14-01] Router 사용 방식 변경

---

packages/server/src/board/board.controller.ts
packages/server/src/board/board.service.ts
packages/server/src/board/entities/board.entity.ts
packages/server/test/board/board.e2e-spec.ts

#84 [06-13] 서버는 사용자 요청에 따라 글 목록을 전송한다.
#65 [09-03] 서버는 검색된 사용자의 글 데이터를 전송한다.
#45 [06-08] 서버는 좋아요 / 좋아요 취소 요청을 받아 데이터베이스의 데이터를 수정한다.
#88 [06-14] 서버는 사용자 요청에 따라 본인이 작성한 게시글을 수정한다.
#89 [06-15] 서버는 사용자 요청에 따라 본인이 작성한 게시글을 삭제한다.
각 메소드에 대한 구현을 TDD (RED-GREEN-REFACTOR) 방식으로 구현함
- 페어 프로그래밍 진행했습니다!
- 개발 기록
- 준섭 : [[준섭] 1116(목) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%A4%80%EC%84%AD%5D-1116(%EB%AA%A9)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)
- 재하 : [[재하] 1116(목) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%9E%AC%ED%95%98%5D-1116(%EB%AA%A9)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)

[BE] [06-08, 06-13, 06-14, 06-15, 09-03] 게시글 CRUD API 구현

---

packages/client/src/app/App.tsx
packages/client/src/shared/lib/types/theme.d.ts
packages/client/src/shared/ui/modals/Modal.tsx
packages/client/src/shared/ui/styles/theme.ts

- Theme 관련하여 `Property 'colors' does not exist on type 'Theme'. ` 에러가 나서 theme.d.ts 파일을 생성하여 해결했습니다.
- Modal
- title과 children을 필수로 받습니다.
- rightButton, leftButton, topButton, explanation은 옵셔널입니다. 
- children의 상하로 margin값을 주지 않아도 됩니다.
Modal 컴포넌트
Modal에 투명도가 적용되어있어서 뒷배경에 #000을 준 상태입니다.
뒤로가기버튼은 아직 버튼컴포넌트가 없는 관계로 넣지 않았습니다.
추후 추가하도록 하겠습니다.
Modal 컴포넌트와 스타일 중 무엇을 상위로 올릴 지 고민하다가 컴포넌트를 상위로 올렸습니다.
이 부분은 통일하는게 좋을 것 같은데 다른 분들 생각은 어떠신지요

[FE] Modal 컴포넌트 구현

---

packages/client/src/shared/ui/inputBar/InputBar.tsx
packages/client/src/shared/ui/modals/Modal.tsx

- 모달 컴포넌트를 화면 정중앙 정렬되게 했습니다.
- 뒤로가기 버튼을 추가했습니다.
- 아직 화살표 버튼이 추가되지 않아 다른 버튼을 임시 추가했습니다.  이후 버튼만 변경하면 정상 작동합니다.
- onClickGoBack을 인수로 받으면 뒤로가기 버튼이 생기고, 인수로 받지 않으면 없어집니다.
onClickGoBack의 더 나은 네이밍이 있는지?
아무거나 막 넣어놨으니 못생겨도 너무 신경쓰지 말아주세요.....
왼쪽위에 버튼이 생긴 것과 모달이 중앙정렬된 것을 봐주십쇼
- 화살표 버튼 머지되면 수정하겠습니다.

[FE] Modal 컴포넌트 수정

---

packages/server/src/auth/decorators/get-user.decorator.ts
packages/server/src/auth/entities/user.entity.ts
packages/server/src/board/board.controller.ts
packages/server/src/board/board.module.ts
packages/server/src/board/board.service.ts
packages/server/src/board/dto/create-board.dto.ts
packages/server/src/board/dto/user-data.dto.ts
packages/server/src/board/entities/board.entity.ts
packages/server/src/main.ts
packages/server/src/utils/aes.util.ts

- [06-08] 서버는 좋아요 / 좋아요 취소 요청을 받아 데이터베이스의 데이터를 수정한다. #45 
- [09-03] 서버는 검색된 사용자의 글 데이터를 전송한다. #65 
- [06-02] 서버는 사용자의 글 데이터를 전송한다. #39
- [06-14] 서버는 사용자 요청에 따라 본인이 작성한 게시글을 수정한다. #88
- [06-15] 서버는 사용자 요청에 따라 본인이 작성한 게시글을 삭제한다. #89
- [08-06] 서버는 전송 받은 글 데이터를 데이터베이스에 저장한다. #60
TypeORM Relation 동작원리 학습 및 비즈니스 로직 개선,,
- POST /board 개선
- PATCH /board/:id
- DELETE /board/:id
- GET /board/by-author
- PATCH /board/:id/like
- PATCH /board/:id/unlike
- 개발기록
- [[재하] 1122(수) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%9E%AC%ED%95%98%5D-1122(%EC%88%98)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)

[BE] user 외래키 활용하도록 메소드 개선, 좋아요 중복 비허용 (조인테이블 생성)

---

packages/client/src/shared/store/userLoginStore.ts
packages/client/src/widgets/landingScreen/index.tsx
packages/client/src/widgets/landingScreen/lib/constants.ts
packages/client/src/widgets/loginModal/index.tsx
packages/client/src/widgets/loginModal/ui/LoginContent.tsx
packages/client/src/widgets/loginModal/ui/RightButton.tsx
packages/client/src/widgets/logoAndStart/index.tsx

#25 #26 #31 #72 
- 아이디와 비밀번호를 입력하면 로그인 버튼이 활성화 된다.
- 로그인 버튼을 누르면 서버로 아이디와 비밀번호를 보낸다.
- 로그인 성공 응답을 받으면 메인페이지로 이동한다.
- 랜딩페이지 배경을 꾸민다.
- 로그인 회원가입 버튼을 만든다.
로그인 기능
https://github.com/boostcampwm2023/web16-B1G1/assets/78800560/506d080c-6fa9-4188-9adb-4d8834fe4ec1
서버와 연동해서 로그인 기능이 정상 작동 하는지 확인할 필요가 있다

[FE] 로그인 및 랜딩 페이지

---

packages/client/src/app/App.tsx

[FE] Svg 인식

---

.github/workflows/deploy.yml
docker-compose.yml
nginx.conf

- [13-04] GitHub Actions을 설정하여 CI/CD 파이프라인을 구축한다.  #115 
- nginx.conf HTTPS 지원하도록 변경
- 버전정보 반영 및 HTTPS 지원되도록 docker-compose 파일 수정
- GitHub Actions 자동 배포 스크립트 작성

[BE] GitHub Action을 이용한 자동 배포

---

.github/workflows/deploy.yml

- [13-04] GitHub Actions을 설정하여 CI/CD 파이프라인을 구축한다.  #115 
다음에 대한 수정
-  #150 
- nginx.conf HTTPS 지원하도록 변경
- 버전정보 반영 및 HTTPS 지원되도록 docker-compose 파일 수정
- GitHub Actions 자동 배포 스크립트 작성

[BE] GitHub Action 스크립트 수정

---

.github/workflows/cicd.yml

- [13-04] GitHub Actions을 설정하여 CI/CD 파이프라인을 구축한다. #115
저 이번에도 안되면 깃헙 접습니다

[Deploy] GitHub Actions를 통한 CI/CD 파이프라인 (수정수정수정수정)

---

docker-compose.yml

- [13-04] GitHub Actions을 설정하여 CI/CD 파이프라인을 구축한다. #115
저 이번에도 안되면 그룹프로젝트 접습니다

[Deploy] GitHub Actions를 통한 CI/CD 파이프라인 (찐막)

---

packages/client/src/pages/Landing/index.tsx
packages/client/src/shared/lib/constants/api.ts
packages/client/src/shared/lib/constants/camera.ts
packages/client/src/shared/lib/constants/index.ts
packages/client/src/shared/ui/buttons/Button.tsx
packages/client/src/shared/ui/modals/Modal.tsx
packages/client/src/widgets/galaxy/index.tsx
packages/client/src/widgets/landingScreen/index.tsx
packages/client/src/widgets/landingScreen/lib/camera.ts
packages/client/src/widgets/loginModal/index.tsx
packages/client/src/widgets/loginModal/ui/LeftButton.tsx
packages/client/src/widgets/loginModal/ui/RightButton.tsx
packages/client/src/widgets/loginModal/ui/TopButton.tsx
packages/client/src/widgets/screen/index.tsx

- 랜딩 페이지에서의 카메라 움직임을 구현했다
- 카메라 관련 상수 중 불필요한 상수를 제거했다
- 로그인 시 엔터키로 로그인 할 수 있도록 했다
랜딩 페이지 카메라 움직임
https://github.com/boostcampwm2023/web16-B1G1/assets/78800560/2382f3b4-c52d-4932-b8e6-9f2760add000
카메라 로테이션을 줄 필요가 없었다는 사실을 깨달았습니다
모달창에서 form을 사용하는 거를 고려해 볼 필요가 있을것 같습니다

[FE] 카메라 움직임

---

packages/client/src/shared/store/usePostStore.ts

- images가 초기화 되지 않아 빌드되지 않던 문제를 해결했다

[FE] 빌드 가능하도록 수정

---

nginx.conf

- 프론트의 라우팅 안되는 문제를 해결하기 위해 Nginx 설정

[Deploy] 프론트 라우팅 문제 해결 (Nginx 설정 변경)

---

packages/client/index.html
packages/client/src/app/Router.tsx
packages/client/src/features/postModal/PostModal.tsx
packages/client/src/features/writingModal/ui/WritingModal.tsx
packages/client/src/pages/Landing/index.tsx
packages/client/src/shared/ui/search/Search.tsx
packages/client/src/widgets/loginModal/index.tsx
packages/client/src/widgets/logoAndStart/index.tsx
packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
packages/client/src/widgets/signupModal/SignUpModal.tsx

- 기존의 pageReducer를 사용한 페이지 이동을, useNavigate를 사용한 페이지 이동으로 변경했습니다.
- 모든 button들에 type을 지정해주었습니다. (button or submit)
- title을 추가했습니다 (탭에 보이는 서비스 이름)
- 파비콘은 이후 로고가 확정되면 추가할 예정입니다. 
- 간단한 수정사항이라 고민한 부분은 없습니다.
- button의 type들이 잘 설정되었는지

[FE] 변경된 라우팅 설정 반영

---

packages/client/src/pages/Home/index.tsx
packages/client/src/shared/ui/underBar/UnderBar.tsx

- UnderBar에 공유하기 버튼을 추가했습니다
- 전체적인 버튼 사이즈를 수정하고, padding을 수정했습니다. 
UnderBar 요소들의 사이즈를 어느정도로 해야 적당할지...
- UndeBar 스타일링

[FE] UnderBar 컴포넌트 UI 변경

---

docker-compose.yml
packages/server/src/board/board.service.ts
packages/server/src/board/entities/image.entity.ts
packages/server/src/config/typeorm.config.ts
packages/server/src/star/star.service.ts

개발기록 참고
```sql
SELECT `Board`.`id` AS `Board_id`,
`Board`.`title` AS `Board_title`,
`Board`.`content` AS `Board_content`,
`Board`.`created_at` AS `Board_created_at`,
`Board`.`updated_at` AS `Board_updated_at`,
`Board`.`like_cnt` AS `Board_like_cnt`,
`Board`.`star` AS `Board_star`,
`Board`.`userId` AS `Board_userId`,
`Board__Board_user`.`id` AS `Board__Board_user_id`,
`Board__Board_user`.`username` AS `Board__Board_user_username`,
`Board__Board_user`.`password` AS `Board__Board_user_password`,
`Board__Board_user`.`nickname` AS `Board__Board_user_nickname`,
`Board__Board_user`.`created_at` AS `Board__Board_user_created_at`,
`Board__likes`.`id` AS `Board__likes_id`,
`Board__likes`.`username` AS `Board__likes_username`,
`Board__likes`.`password` AS `Board__likes_password`, …
```

[BE] GET /star, GET /post/:id 쿼리 최적화 (+ docker 컨테이너 재실행 설정)

---

packages/server/src/board/board.controller.ts
packages/server/src/board/board.service.ts
packages/server/src/board/decorators/swagger/update-board-swagger.decorator.ts
packages/server/src/board/dto/create-board.dto.ts
packages/server/src/star/star.controller.ts
packages/server/src/star/star.service.ts

- [08-10] 서버는 게시글 테이블(DB) 접근 시 필요하다면 트랜잭션을 적용한다. #112
- [08-09] 서버는 게시글 테이블(DB) 접근에 관한 에러를 처리한다. #111
개발기록 참고
별글 등록
GET /post/:id로 조회. 복호화해보니 content도 잘 들어감
image filename으로 Object Storage에도 잘 들어간 것 확인
image 테이블에도 정보 잘 들어간 것 확인
PATCH /post/:id로 별글 수정. 선별적으로 content, file만 수정해보자.
이후 기존의 filename으로 조회해보면 정상적으로 이전 파일이 삭제된 것을 확인할 수 있음.
데이터베이스에서도 기존의 image 레코드(id 67)가 삭제되고 68번이 생성된 것을 확인할 수 있음.
GET /post/224로 조회해보면 content도 잘 바뀐 것을 확인할 수 있고, image url도 바뀐 것으로 잘 변경되어 있음. 성공!
---
like 레코드 자동 삭제 확인을 위해 좋아요를 하나 누르고 테스트해보았다.
255번 게시글 생성
좋아요
잘 반영되었고
조인 테이블에도 추가됨 (255번 게시글, 5번 유저)
DELETE /post/225
당연히 게시글 삭제 됐고
이미지도 찾아보니 없음. 잘 삭제됨
Image 테이블에서도 정상적으로 레코드가 삭제됨
Like 조인테이블에서도 정상적으로 삭제됨
마지막으로 Star 컬렉션에서도 정상적으로 삭제됨. 끝!
---
POST로 별글 등록. 이제 star는 필수 입력값으로 바뀌었다.
PATCH /star/226으로 해당 별글의 별 스타일을 변경.
마음대로 속성을 …

[BE]  PATCH & DELETE /post/:id 개선 및 트랜잭션 적용, PATCH /star/:id 구현

---

packages/server/src/interceptor/log-color.code.ts
packages/server/src/interceptor/log.interceptor.ts
packages/server/src/interceptor/transaction.interceptor.ts

- [17-01] 서버는 요청과 응답에 대한 로그를 남긴다. #197 
로그에 컬러 추가
중간에 발생한 에러 로그를 남기기 위해 catchError추가

[BE] Log 컬러 지정 및 catchError 추가

---

.github/workflows/cicd.yml

- 배포 OS에 맞는 sharp 설치를 위한 구문 추가

[Deploy] sharp 플랫폼 에러 핫픽스

---

.github/workflows/cicd.yml
.gitignore
Dockerfile-was

[Deploy] week4 배포

---

packages/server/src/board/board.controller.ts
packages/server/src/board/board.service.ts
packages/server/src/board/decorators/swagger/get-is-liked-swagged.decorator.ts

좋아요 한 상태면 true
좋아요 취소 요청
좋아요 안한 상태이므로 false

[BE] 로그인한 사용자의 좋아요 여부 조회(GET /post/:id/is-liked)

---

Dockerfile-was

- [13-01] Dockerfile을 통해 docker 이미지를 build하고 Docker Hub에 push한다. #75
- [13-02] 클라우드 인스턴스에서 docker 이미지를 pull하여 실행한다. #113
줄어든 용량ㅎ
- 개발 기록
- [[재하] 1203(일) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%9E%AC%ED%95%98%5D-1203(%EC%9D%BC)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)
- 학습 기록
- [docker image 최적화(멀티스테이징)](https://velog.io/@qkrwogk/Kubernetes-%EA%B8%B0%EC%B4%88minikube-docker-image-%EC%B5%9C%EC%A0%81%ED%99%94%EB%A9%80%ED%8B%B0%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%A7%95-AWS-IAM-EC2)

[BE] docker 이미지 최적화

---

packages/server/src/auth/auth.controller.ts

- OAuth signin시 첫 로그인이면 닉네임 설정 라우팅으로 이동
- 회원가입된 사용자라면 쿠키 발급 후 /login 라우팅으로 이동
- OAuth signup 완료시 /login 라우팅으로 이동

[BE] OAuth Api 결과에 redirect 추가

---

nginx.conf

[Deploy] nginx.conf에 client-max-body-size 옵션 추가

---

packages/client/src/entities/like/Like.tsx
packages/client/src/shared/ui/inputBar/InputBar.tsx
packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx

[FE] 닉네임 모달, 좋아요 버그 수정

---

packages/client/src/entities/like/Like.tsx
packages/client/src/shared/apis/login.ts
packages/client/src/shared/ui/inputBar/InputBar.tsx
packages/client/src/shared/ui/underBar/UnderBar.tsx
packages/client/src/widgets/galaxyCustom/ui/SampleScreen.tsx
packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx

[FE] hofix 반영

---

packages/server/src/admin/admin.controller.ts
packages/server/src/admin/admin.module.ts
packages/server/src/admin/admin.service.ts
packages/server/src/app.module.ts

- 백엔드에서 admin 모듈 생성 (어드민 페이지 API 요청 처리용)

[BE] 백엔드에서 admin 모듈 생성

---

packages/client/src/pages/Home/index.tsx
packages/client/src/shared/ui/underBar/UnderBar.tsx
packages/client/src/widgets/loginModal/index.tsx

[FE] 닉네임 받는 시점 변경

---

packages/client/src/shared/store/useCameraStore.ts

🎨 Reflect feedback

---

packages/client/src/shared/apis/login.ts
packages/client/src/shared/lib/constants/camera.ts
packages/client/src/shared/store/useCameraStore.ts
packages/client/src/shared/ui/inputBar/InputBar.tsx
packages/client/src/shared/ui/slider/Slider.tsx
packages/client/src/widgets/galaxy/lib/modules/instances.tsx
packages/client/src/widgets/galaxyCustom/index.tsx
packages/client/src/widgets/galaxyCustom/ui/LeftButton.tsx
packages/client/src/widgets/galaxyCustom/ui/SampleScreen.tsx
packages/client/src/widgets/galaxyCustom/ui/Sliders.tsx
packages/client/src/widgets/galaxyCustom/ui/TopButton.tsx
packages/client/src/widgets/galaxyCustom/ui/index.ts
packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx

- 카메라 최대거리를 설정해 은하에서 특정 거리보다 멀어지지 않도록 했다
- 은하 커스텀에서 은하 초기상태로 돌아가는 초기화와 현재 은하 상태로 돌아가는 새로고침 버튼을 만들었다
- 서버로부터 닉네임을 받아오는 시점을 변경했다
은하 커스텀 새로고침 버튼 색 괜찮나요

[FE] 카메라 최대거리 설정, 은하 커스텀 추가기능

---

packages/admin/src/components/Board/Board.tsx
packages/admin/src/components/SystemInfo/SystemInfo.tsx
packages/admin/src/components/shared/Button.tsx
packages/server/src/admin/admin.service.ts

- 개발 기록
- [[재하] 1205(화) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%9E%AC%ED%95%98%5D-1205(%ED%99%94)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)

[BE] 어드민 페이지 디스크 사용량 조회, 게시글 상세 조회

---

packages/admin/src/components/Board/Board.tsx
packages/admin/src/components/SystemInfo/SystemInfo.tsx
packages/server/src/admin/admin.service.ts
packages/server/src/star/star.service.ts

- GET /star API 인터페이스 일부 변경
- 어드민 프론트, 백 피드백 받은 부분 코드 개선

[BE] GET /star API 인터페이스 수정, 어드민 기능 리팩토링

---

packages/client/src/widgets/signupModal/ui/IdInputContainer.tsx

- 회원가입시 중복확인 버튼의 타입이 지정되지 않아 새로고침 되던 문제를 해결했다

[FE] HotFix

---

packages/server/src/board/board.controller.ts
packages/server/src/board/board.module.ts

- board 컨트롤러 안불러지는 문제 해결
- exception 필터를 컨트롤러 전체로 옮김

[BE] Hotfix

---

packages/client/src/pages/Home/index.tsx
packages/client/src/pages/Home/ui/UpperBar.tsx
packages/client/src/shared/ui/underBar/UnderBar.tsx

- 닉네임 처리 방식을 변경했다
- 은하 형태를 받아와 처리하는 부분에서 처리 되지 않던 상황을 추가했다

[FE] 예외사항 처리, 닉네임 처리 방식 변경

---

packages/client/src/pages/Home/index.tsx
packages/client/src/shared/apis/galaxy.ts
packages/client/src/shared/store/useCustomStore.ts
packages/client/src/shared/store/useGalaxyStore.ts
packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
packages/client/src/widgets/galaxyCustomModal/ui/LeftButton.tsx
packages/client/src/widgets/galaxyCustomModal/ui/TopButton.tsx

- zustand의 get을 사용해 값이 다른 경우에만 set 하도록 수정했다

[FE] zustand get 사용

---

packages/client/src/pages/Home/index.tsx

[FE] Build fix

---

packages/client/src/widgets/starCustomModal/StarCustomModal.tsx

close #62 
close #58 
close #49 
- shape 인덱스 방식으로 수정
- api 리턴 status 변경
ㅋ ㅑ

[FE] 별 생성 api 수정

---

packages/client/src/entities/posts/apis/getMyPost.ts
packages/client/src/entities/posts/ui/Posts.tsx
packages/client/src/features/controls/Controls.tsx
packages/client/src/features/star/lib/constants/index.ts
packages/client/src/widgets/galaxy/lib/constants/index.ts
packages/client/src/widgets/screen/index.tsx

- 카메라 속도 조정
- 별 최소 크기 조정
- 은하 별 개수 조정
- 글 생성, 삭제 시 데이터 리페칭
- 휠 스피드 값 조정
글 생성 삭제 시 데이터 리페칭을 해오기 위해 view가 바뀔 때마다 바뀐 view가 MAIN이면 데이터를 다시 가져오도록 해주었습니다.
데이터 리페칭
같이 봤으니까 생략

[FE] 값 조절, 데이터 리페칭 구현

---

packages/client/src/widgets/screen/index.tsx
packages/client/src/widgets/screen/ui/CameraLight.tsx
packages/client/src/widgets/screen/ui/index.ts

- 카메라를 따라 다니는 광원을 추가해 우주를 좀 더 꾸몄다

[FE] 카메라 광원

---

packages/admin/src/App.tsx
packages/admin/src/components/ExceptionStatistics/Chart/Chart.tsx
packages/admin/src/components/ExceptionStatistics/ExceptionStatistics.tsx
packages/admin/src/components/ExceptionStatistics/Filter/Filter.tsx
packages/admin/src/components/ExceptionStatistics/exception.interface.ts
packages/server/src/admin/admin.controller.ts
packages/server/src/admin/admin.service.ts

ExceptionStatistics 추가
하위 컴포넌트로 Filter, Chart 추가
Filter 컴포넌트에 경로, 에러 종류, 날짜로 필터링 기능 추가
비동기로 동작하는 state 관리의 어려움이 있었음 -> 동민님 도움으로 해결
모든 조건으로 검색
에러로 필터링
날짜로 필터링

[BE] ExceptionStatistics 컴포넌트 Filter 컴포넌트 구현

---

packages/server/src/auth/auth.controller.ts
packages/server/src/auth/auth.service.ts
packages/server/src/auth/cookie-auth.guard.ts
packages/server/src/auth/decorators/get-user.decorator.ts
packages/server/src/auth/decorators/swagger/sign-in-swagger.decorator.ts
packages/server/src/auth/dto/signin-user.dto.ts
packages/server/src/auth/enums/user.enum.ts
packages/server/src/auth/pipes/StatusValidationPipe.ts
packages/server/src/util/auth.util.ts

Auth 모듈 안에서 발생하는 에러 메세지 영어로 수정\

[BE] Auth 모듈 에러 메세지 영어로 수정

---

packages/server/src/board/board.service.ts
packages/server/src/galaxy/galaxy.service.ts
packages/server/src/sentiment/sentiment.service.ts
packages/server/src/star/star.service.ts

[BE] 에러 메시지 포맷 통일

---

packages/server/src/board/board.controller.ts
packages/server/src/board/board.module.ts
packages/server/src/board/board.service.ts
packages/server/src/board/file.service.ts

[BE] board 트랜잭션 제어 방식 변경, 파일 관련 메소드 서비스로 분리

---

packages/client/src/features/postModal/ui/PostModal.tsx
packages/client/src/shared/ui/search/Search.tsx
packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
packages/client/src/widgets/galaxyCustomModal/ui/RightButton.tsx
packages/client/src/widgets/loginModal/LoginModal.tsx
packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
packages/client/src/widgets/starCustomModal/ui/SentimentButton.tsx
packages/client/src/widgets/underBar/UnderBar.tsx
packages/client/src/widgets/upperBar/UpperBar.tsx

- 버튼 연속 클릭 방지 기능 구현
boolean state 하나 선언해서 API 처리 끝날때까지 버튼 disabled 시켜줬습니다. 
버튼 클릭으로 API 호출하는 부분들은 다 수정한 것 같은데 혹시 빠뜨린게 있는지 모르겠네요 흑
호옥시나 빠뜨린 버튼이 있을지
버튼 디자인과 동일하므로 생략하겠습니다.

[FE] 버튼 연속 클릭 방지 기능 구현

---

packages/client/src/app/App.tsx
packages/client/src/features/postModal/ui/PostModal.tsx
packages/client/src/shared/ui/alertDialog/AlertDialog.tsx
packages/client/src/widgets/starCustomModal/apis/getSentimentColor.ts

- 잘못된 import 문 수정
- 잘못된 try 문 수정

[FE] 버그 수정

---

packages/server/src/auth/entities/user.entity.ts
packages/server/src/auth/enums/user.enum.ts

유저 상태값에 NEW 추가
프론트에서 코치마크를 띄워주는데 사용할 예정
새로 회원가입한 회원의 check-signin 결과
이 status 값이 new면 코치마크를 띄워주고 다 끝나면 다시 status를 'public'으로 바꿔주면 됨


[BE] User Status값 NEW 추가

---

packages/client/src/shared/ui/alert/Alert.tsx
packages/client/src/widgets/loginModal/ui/TopButton.tsx
packages/client/src/widgets/screen/Screen.tsx

- 사용하지 않게된 전역 환경을 사용하던 일부 코드를 수정했다
- 빌드 가능하도록 고쳤다

[FE] Fix bug

---

packages/client/src/pages/Home/Home.tsx
packages/client/src/widgets/warpScreen/WarpScreen.tsx
packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx

- FadeoutScreen을 WarpScreen 내로 이동시켰습니다.
- WarpScreen에서 isSwitching이 false면  FadeoutScreen을 반환합니다.
- 큰 고민이 필요한 부분은 아니엇슴다
- WarpScreen.tsx

[FE] WarpScreen과 FadeoutScreen 통합

---

packages/client/src/shared/hooks/useCheckNickName.ts
packages/client/src/widgets/underBar/UnderBar.tsx
packages/client/src/widgets/upperBar/UpperBar.tsx

- useLocation에서 url의 한글을 읽지 못하는 문제가 있어 useParams를 사용하도록 수정했다
- guest의 경우 검색바를 보이지 않도록 했다
- 본인 은하에서만 코치버튼이 보이도록 수정했다
- 내 페이지가 아닐때 display none인 버튼이 생성되지 않도록 했다

[FE] 버그 수정, 일부 기능 숨기기

---

packages/client/src/entities/like/Like.tsx
packages/client/src/features/postModal/ui/PostModal.tsx
packages/client/src/features/writingModal/ui/WritingModal.tsx
packages/client/src/shared/apis/search.ts
packages/client/src/shared/ui/alert/Alert.tsx
packages/client/src/shared/ui/alertDialog/AlertDialog.tsx
packages/client/src/shared/ui/modal/Modal.tsx
packages/client/src/shared/ui/textArea/TextArea.tsx
packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
packages/client/src/widgets/starCustomModal/ui/SentimentButton.tsx
packages/client/src/widgets/underBar/UnderBar.tsx
packages/client/src/widgets/upperBar/UpperBar.tsx

- 버튼 disable 되고 다시 돌아오지 않는 버그 수정
- 로그인 안하고 좋아요 클릭 시 알럿창 표시
- 글 확인 및 작성 모달에서 몇가지 수정
1. ul, ol 스타일 보이게 수정
2. 긴 문자열 작성 시 가로 스크롤바 생기던 현상 줄바꿈 되도록 수정
3. 사진 있던 글에서 본문이 쓸데없는 높이를 먹고 있던 현상 수정
- 로그인 안한 상태에서는 로그아웃 버튼 보이지 않게 수정
- 검색 API를 새로 생긴 API를 사용하는 방식으로 재구현
css에 word-break 라는 속성이 있더라구요 이걸 통해서 줄바꿈을 구현해줬습니다.

[FE] 버그 수정, 디자인 변경, 좋아요 알럿창 구현

---

packages/client/src/shared/ui/modal/Modal.tsx
packages/client/src/widgets/galaxyCustomModal/GalaxyCustomModal.tsx
packages/client/src/widgets/loginModal/LoginModal.tsx
packages/client/src/widgets/starCustomModal/StarCustomModal.tsx
packages/client/src/widgets/underBar/UnderBar.tsx
packages/client/src/widgets/upperBar/UpperBar.tsx
packages/client/src/widgets/warpScreen/WarpScreen.tsx

- 병합 과정에서 모달이 form 안에서 생성되지 않던 문제가 있어 modal이 form을 상속하도록 변경했다
- 빌드 가능하도록 수정했다

[FE] 모달 문제 해결

---

packages/client/src/app/global.css
packages/client/src/features/postModal/ui/ImageSlider.tsx
packages/client/src/shared/ui/buttons/Button.tsx
packages/client/src/shared/ui/buttons/IconButton.tsx
packages/client/src/shared/ui/buttons/TextButton.tsx

- 모달이 form으로 바뀌면서 모든 버튼의 타입을 기본적으로 button으로 바꿔줬다
- body의 배경색을 추가해 가성비 있게 warp를 개선했다
- 버튼을 사용할때 Button을 상속받거나 type을 button으로 지정해 줘야 합니다

[FE] 버튼 새로고침 문제 해결, warp 개선

---

packages/client/src/features/postModal/ui/ImageSlider.tsx

- 이미지 슬라이더 하단 페이지네이션이 작동하지 않던 문제를 해결했다

[FE] 페이지네이션 버그 해결

---

packages/client/src/pages/Home/Home.tsx

- 뒤로가기시 view 설정이 바뀌지 않아 생긴 문제를 해결했다
하단바와 상단바가 지워지는 상태에서 뒤로가기시 여전히 하단바와 상단바가 보이지 않는 문제가 있었다.
뒤로가기는 전역환경 view를 바꿔주지 않기 때문이었다.
이에 useLocation으로 path 정보를 읽어와 하단바와 상단바를 보여줘야 하는 상황인경우 view을 MAIN으로 설정하도록 했다.

[FE] 뒤로가기 오류 해결

---

packages/client/src/widgets/shareModal/ShareModal.tsx

- 공유모달에서 status 변경 시 새로고침되면서 에러 발생하던 문제를 type="button"으로 수정했습니다.

[FE] 버튼 에러 수정

---

packages/server/src/auth/auth.service.ts

- check-nickname api 유저 status값 리턴하도록 변경

[BE] check-nickname API 리턴값 변경

---

packages/server/src/auth/auth.service.ts

[BE] Search Api 유저 status private이 아니면 나오도록 수정

---

packages/server/src/auth/auth.service.ts

[BE] be-develop 병합

---

packages/client/index.html
packages/client/src/features/writingModal/ui/WritingModal.tsx
packages/client/src/pages/Home/Home.tsx
packages/client/src/pages/Landing/Landing.tsx
packages/client/src/shared/apis/search.ts
packages/client/src/shared/lib/constants/error.ts
packages/client/src/shared/routes/ModalRoot.tsx
packages/client/src/widgets/upperBar/UpperBar.tsx

- 비공개 은하 검색 버그 수정
- 모달 포탈 버그 수정
모달 루트를 동적으로 생성하니 계속해서 모달 루트가 생성되기 전에 모달 포탈이 모달 루트를 찾으려는 현상이 발생해 그냥 index.html에 모달 루트를 생성해두는 예전 방식으로 돌아갔습니다.
-> 그에따라 전체화면 문제가 다시 발생하였고,  전체화면을 하는 방식을 react-full-screen을 이용하는 방식이 아닌 js의 requestFullscreen을 이용하는 방식으로 변경하여 문제를 해결했습니다.

[FE] 비공개 은하 검색 버그 수정

---

packages/client/src/pages/Home/Home.tsx
packages/client/src/widgets/starCustomModal/lib/generateStarPosition.ts

- 새로고침시 발생하는 문제 해결
- 별 생성 위치 확장

[FE] 버그 해결

---

packages/client/src/entities/posts/ui/Post.tsx
packages/client/src/features/coachMarker/CoachButton.tsx
packages/client/src/pages/Home/Home.tsx
packages/client/src/shared/ui/inputBar/InputBar.tsx
packages/client/src/shared/ui/textArea/TextArea.tsx

- 기존 코드에서 theme를 import 해서 쓰던 부분을 해결했다
- 글쓰기, 우주 커스텀 등에서 새로고침시 상단바, 하단바가 생기는 문제 해결

[FE] Theme 사용

---

packages/client/src/app/global.css
packages/client/src/entities/posts/ui/Post.tsx
packages/client/src/pages/Home/Home.tsx
packages/client/src/shared/lib/types/button.ts
packages/client/src/shared/lib/types/index.ts
packages/client/src/shared/lib/types/star.ts
packages/client/src/shared/lib/types/warp.ts
packages/client/src/shared/ui/buttons/Button.tsx
packages/client/src/shared/ui/buttons/generateButtonStyle.ts
packages/client/src/widgets/warpScreen/WarpScreen.tsx
packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx

- 피드백을 받았던 타입으로 분리하는 작업은 전체적으로 해줬다
- Post의 라벨 부분이 theme를 받아오지 못하는 문제를 해결했다
- 폰트 경로 수정
- button, input, textarea 에서 폰트 적용

[FE] 타입 사용, 오류 해결, 폰트 적용

---

packages/client/src/widgets/writingModal/ui/Images.tsx

[FE] 빌드 에러 수정

---

packages/client/index.html
packages/client/src/widgets/galaxy/lib/modules/instances.tsx
packages/client/src/widgets/writingModal/ui/WritingModal.tsx

[FE] 파비콘. 린트 fix

---

packages/client/src/widgets/galaxy/lib/modules/instances.tsx

- 배결별에 거리 제한이 설정되지 않아 최소크가 너무 작아지는 문제를 해결했다
전
https://github.com/boostcampwm2023/web16-B1G1/assets/78800560/94eba6f8-04d2-4dc4-a459-19d44db0aedc
후
https://github.com/boostcampwm2023/web16-B1G1/assets/78800560/b51ce1ba-e736-4092-b1b1-be4ec93af97f

[FE] 배경별 Distance limit

---

packages/server/src/board/dto/create-board.dto.ts
packages/server/src/exception-filter/http.exception-filter.ts
packages/server/src/interceptor/log.interceptor.ts

- 로그 인터셉터, 익셉션 필터 로깅 추가
- 게시글 maxlength 추가

[HotFix] 로깅 문제 해결, 게시글 maxlength 문제 해결
