boostcampwm2023/web16-B1G1

- Dockerfile
#75 [13-01] Dockerfile 작성
- node:20-alpine 이미지를 기반으로 BE 프로젝트를 build하여 3000번 포트 열고 실행
```ts
FROM node:20-alpine
WORKDIR /app
ADD . /app
RUN yarn workspace server build
EXPOSE 3000
ENTRYPOINT ["yarn", "workspace", "server", "start:prod"]
```
```bash
docker build -t qkrwogk/web16-b1g1-be --platform linux/amd64 .
docker login -u qkrwogk
docker push qkrwogk/web16-b1g1-be
docker pull qkrwogk/web16-b1g1-be
docker container run --name be -d -p 80:3000 qkrwogk/web16-b1g1-be
```
NCP 환경에 첫 배포를 성공했다!
해당 Dockerfile로 docker build하여 이미지를 생성하고, docker hub에 push 후 
클라우드 Server 인스턴스에서 이를 pull 하여 실행하면 된다. 
로컬 환경(macOS, arm64)과 클라우드 인스턴스의 하드웨어 플랫폼(ubuntu, amd64)이 달라
docker 이미지를 옵션 없이 생성해서 옮기면 실행이 되지 않는 문제가 있었다. 
따라서 docker build 시 꼭 다음과 같이 `--platform`으로 실행환경의 플랫폼을 명시해줘야 한다.
```bash
docker build -t …
```
> [BE] [13-01] Dockerfile 생성 및 클라우드 환경에 배포

- packages/server/src/board/board.controller.ts
- packages/server/src/board/board.service.ts
- packages/server/test/board/board.e2e-spec.ts
#39 [06-02] 서버는 사용자의 글 데이터를 전송한다. 
- GET /board/:id 실패하는 테스트 코드 작성
- 테스트 통과하도록 로직 구현
- 함수명 변경, 리턴 타입 명시 등 리팩토링 및 Not Found 에러 처리
- [앞선 PR](https://github.com/boostcampwm2023/web16-B1G1/pull/82)과 동일하게 TDD로 GET /board/:id 구현
- RED, GREEN, REFACTOR 3 단계로 구현 수행 및 커밋함
[[재하] 1115(수) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%9E%AC%ED%95%98%5D-1115(%EC%88%98)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)
> [BE] [06-02] GET /board/:id TDD로 구현 #39

- packages/client/src/components/feature/SpaceWarp/indes.tsx
- packages/client/src/components/feature/SpaceWarp/index.tsx
- packages/client/src/components/feature/Star/index.tsx
- packages/client/src/constants/spaceWarp.ts
- packages/client/src/pages/Home/index.tsx
#98 
- 공간을 통과하는 듯한 느낌을 주는 애니메이션 생성
- useFrame 부분
https://github.com/boostcampwm2023/web16-B1G1/assets/80266418/76a86386-a89d-49a2-9880-90dede04b58f
- 색상같은 것은 임시로 해두었습니다.
- 디자인 확정이 아니라 대략적인 느낌만 봐주시면 될 것 같습니다.
- 몇 초 지난 후 화면의 중앙부터 서서히 흰색으로 변하는 애니메이션을 구현할까 했는데... 
-  화면이 한 번에 흰색으로 변하는 것까진 됐는데, 중앙부터 서서히 변하는 것은 아직 구현하지 못했습니다.
- 하단에 엄청 쎈 광원을 두어 밑으로 내려가면서 점점 하얘지는.. 그런 연출도 가능할까요?? 
- 아무튼 이 부분도 확정이 아니라 그냥 시도해본거라 커밋은 하지 않았습니다. 
- 수정하면 좋을 부분이나, 처음과 끝에 넣으면 좋을 애니메이션이 있다면 알려주세요.
- 기존 backgroundStars 컴포넌트를 변형하여 만들었습니다.
- positions 부분에 차이가 있습니다.
- 점이 아닌 선이므로 x, y, z 좌표를 두 번씩 넣습니다.  
- lineSegments와 LineBasicMaterial을 사용합니다.
- 우주공간의 x, z 범위는 줄이고 y 범위를 늘렸습니다. 
- y범위의 끝에서 카메라가 서서히 내려가는 식으로 동작합니다. 
- 카메라가 우주의 끝을 넘어서면 더이상 애니메이션이 보이지 않습니다.
- 실제로는 몇 초간만 보여주고 끝낼 화면이라 그 부분은 신경쓰지 않았습니다.
> [FE] [04-09] 페이지 간 이동시 보여줄 화면 제작

- packages/server/src/auth/auth.controller.ts
- packages/server/src/auth/auth.service.ts
- packages/server/src/auth/decorators/user-constraints.decorator.ts
- packages/server/src/auth/dto/signin-user.dto.ts
- packages/server/src/auth/dto/signup-user.dto.ts
- packages/server/src/auth/enums/jwt.enum.ts
- packages/server/src/auth/enums/user.enum.ts
- packages/server/src/config/jwt.config.ts
#27 [04-04] 데이터베이스에서 로그인 데이터로 조회를 하여 비교한다.
- 파일 이름 변경
- signup-contraints.decorator.ts -> user-constraints.decorator.ts
- signup.enum.ts -> user.enum.ts
- SignInUserDto의 username, password에 대하여 ClassValidator 추가
- Auth Controller, Service에서 Redis 관련 코드 제거
- api 삭제
- Service에서 Redis get, set 메서드 삭제
- RefreshToken 발급 로직 추가
- Service에서 RefreshToken 발급 및 토큰 Redis에 저장
- Controller에서 RefreshToken도 쿠키에 저장 응답 전송
- JwtEnum 추가 및 하드코딩 부분들 Enum값으로 수정
재하님 저번 피드백 대로 일단 Redis와 직접적으로 통신하는 api를 삭제하고 Service 메서드도 삭제했습니다! 
Service의 특정 로직 안에서 필요시 redisRepository의 로직을 사용하는 느낌으로 하면 될 것 같습니다.
로그인 요청 보낼 시 쿠키에 토큰이 담긴 모습
이 두 토큰의 값을 디코딩 해보았다.
1. accessToken
2.  refreshToken
정보가 잘 담겨있는 모습을 확인했다.
유효 기간도 accessToken은 1시간, refreshToken은 하루가 잘 적용되어 있었다.
redis에도 저장이 잘 된 모습을 보였다.
첫 명렁어를 봤을 때 key가 없었고, signin후 다음 명령어를 실행하니 …
> [BE] SignIn시 RefreshToken 발급 및 Redis에 저장

- packages/server/src/board/board.controller.ts
- packages/server/src/board/board.service.ts
- packages/server/src/board/dto/create-board.dto.ts
- packages/server/src/board/dto/create-image.dto.ts
#88 [06-14] 서버는 사용자 요청에 따라 본인이 작성한 게시글을 수정한다. 
#60 [08-06] 서버는 전송 받은 글 데이터를 데이터베이스에 저장한다. 
#61 [08-07] 사진 정보는 스토리지 서버에 저장한다. 
- 개발 기록
- [[재하] 1121(화) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%9E%AC%ED%95%98%5D-1121(%ED%99%94)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)
> [BE] board 모듈 입력값 유효성 검증

- packages/client/src/shared/ui/search/Search.tsx
- onClick, placeholder, inputState, setInputState를 props로 받는 Search 컴포넌트 생성
- 원래는 inputState와 setInputState가 아닌 onChange만 받아왔는데, input 내용 유무에 따라 버튼 상태를 변경하기 위해 useState를 받아오는 식으로 변경했습니다. 더 좋은 방법이 있다면 알려주세요.
- width는 100%로 주었고, width가 늘어남에 따라 중간의 input의 width가 함께 늘어납니다.
- input이 비어있으면 버튼이 비활성화됩니다.
props 받아오는 부분에서 수정할 점이 있다면 알려주세요 
- 뒷배경을 #000으로 주어 테스트했습니다.
https://github.com/boostcampwm2023/web16-B1G1/assets/80266418/7e36521e-5191-4f12-8b86-ba520e68a364
- Layout background 부분 색을 primary.disabled로 줬더니 뭔가 이상해서 일단 #05021F로 해두었습니다. 뭐가 문제일까요.. ㅜ 
-> 수정했습니다 ! figma에 색 연결이 안되어있었네요 
- @bananaba
- 버튼이 active될 때 조금 커지는 것 같습니다. 수정해주시면 감사하겠습니다
- PR에도 방금 달아놓은 내용이지만 버튼이 disabled 상태일 때는 `cursor: default`로 하면 좋을 것 같은데 다른 분들 의견은 어떠신가요?
> [FE] Search 컴포넌트 생성

- packages/server/src/auth/auth.controller.ts
- packages/server/src/auth/auth.service.ts
- packages/server/src/auth/cookie-auth.guard.ts
- packages/server/src/auth/enums/user.enum.ts
- packages/server/src/auth/redis.repository.ts
#35 [05-04] 로그인을 한 사용자라면 Redis의 Refresh Token 정보를 삭제한다.
- RedisController에 del 메서드 추가
- AuthController의 signout api에 CookieAuthGuard 추가
- authService.signout으로 req.user 정보 넘김
- Redis의 키값을 삭제하는 authService.signout 메서드 작성
- AuthController signout 로직에 enum 적용
일단 enum을 사용하여 해놓긴 했는데 재하님이 저번에 말씀해주신 것처럼 어디까지 enum을 사용할 것인지는 저희끼리 합의가 필요할 듯 싶습니다!
[개발 기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%A4%80%EC%84%AD%5D-1122(%EC%88%98)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D-%E2%80%90-SignOut%EC%8B%9C-%ED%86%A0%ED%81%B0-%EC%A0%9C%EA%B1%B0)
> [BE] SignOut시 토큰 제거

- packages/client/src/shared/ui/inputBar/InputBar.tsx
- packages/client/src/shared/ui/toast/Toast.tsx
- Toast 컴포넌트를 구현했습니다.
- props는 토스트의 텍스트를 받는 children 하나만 있습니다.
- 2초가 지나면 자연스럽게 사라집니다.
- keyframe 부분 코드만 있어도 동작화면은 같습니다. 
- visible이라는 useState를 만들고 setTime을 사용한 이유는 아래와 같습니다.
- `visible:none`으로만 처리하지 않고 아예 없애버리고 싶어서 3초가 지나면 컴포넌트가 null을 리턴하도록 했습니다. 
- 다른 분들의 의견도 궁금하네요.
- animation duration이 2초인데 setTimeout이 3초인 이유는, 사라지는 animation이 1초간 지속되기 때문입니다. 
- setTimout에 2초를 주면 애니메이션이 시작되기 전에 null을 리턴해서 애니메이션이 안보입니다 🥹
- `position: absolute`를 주어 위치를 고정했습니다. 
setTimeout 부분
https://github.com/boostcampwm2023/web16-B1G1/assets/80266418/22b69d45-6c74-4d63-af9f-9c037b7de6a0
솔직히 토스트좀 귀여운것같아요
> [FE] Toast 컴포넌트 구현

- packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
- packages/client/src/widgets/signupModal/SignUpModal.tsx
#8 
- 회원가입 모달과 거의 같은 형식으로 닉네임 설정 모달을 만들었습니다. 
- input이 채워졌을 경우만 버튼이 활성화됩니다.
- SignUpModa의 signUpButton 부분 코드를 더 간단하게 바꾸었습니다.
NickNameSetModal
https://github.com/boostcampwm2023/web16-B1G1/assets/80266418/502a1a9f-cfea-4071-bf8d-70a5cf35751f
혹시 회원가입 모달 PR을 아직 안보셨다면 그것부터 봐주세요
> [FE] 닉네임 설정 모달 구현 

- packages/server/src/auth/auth.controller.ts
- packages/server/src/auth/auth.service.ts
- packages/server/src/utils/auth.util.ts
- [03-06] 서버는 네이버로 로그인 기능을 제공한다. #106 
깃헙 로그인때 사용했던 부분을 리팩토링 해서 OAuth 로그인 로직으로 통합했습니다.
url에 :service로 @Param으로 서비스 명을 받아와서 해주는 식으로 함수 재사용을 최대한 하려고 했습니다.
naver에서 accessToken으로 유저 정보 가져오면 아래와 같이 id값이 uuid? 값이 나옵니다. 이걸 그냥 회원가입 하는데 username으로 썼습니다.
`/auth/naver/signup`으로 회원가입 완료
다음부터 네이버 로그인 하면 JWT 발급됨
> [BE] 네이버 로그인 구현

- packages/client/src/shared/ui/modals/Modal.tsx
- packages/client/src/shared/ui/search/Search.tsx
- packages/client/src/shared/ui/styles/theme.ts
- 투명도를 준 색상코드를 theme.ts에 추가했습니다.
- [참고 링크](https://mong-blog.tistory.com/entry/CSS-hex-%EC%BB%AC%EB%9F%AC%EC%97%90-%ED%88%AC%EB%AA%85%EB%8F%84%EB%A5%BC-2%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95)
- bdp01 색상에 80의 투명도가 들어간 경우 bdp01_80과 같은 이름으로 설정했습니다. 앞으로 투명도가 필요한 색상코드가 있다면 모두 이런 형식으로 추가해주시면 될 것 같습니다.
- Modal과 Search의 Layout opacity를 없애고, background-color를 투명도 준 색상으로 변경했습니다.
- opacity를 줄 경우 해당 요소의 자식 요소들까지 모두 투명해지는 문제가 있었습니다.
- opacity를 주지 않고, background color에 투명도가 적용된 색상이 적용된다면 그 요소에만 투명도가 적용됩니다.
뒷배경의 색상과 관계없이 input의 색은 유지되는 것을 볼 수 있습니다.
> [FE] 모달창 자식요소 투명해지는 문제 해결

- packages/server/src/auth/auth.controller.ts
- packages/server/src/utils/auth.util.ts
- [03-07] 서버는 구글로 로그인 기능을 제공한다. #105 
OAuth 재사용하게 코드 고쳐놓으니 개발이 아주 빨랐네요. 코드를 별로 고친게 없습니다 ㅎ
근데 재하님 그 이 각 서비스에 OAuth 클라이언트 만들 때 url을 localhost 버전이랑 저희 별글.site 버전 두 개를 만들어서 각각의 클라이언트 ID와 secret이 다릅니다.
그래서 로컬 환경이랑 프로덕션 환경 .env를 수정하긴 해야합니다!
google에서 accessToken으로 유저 정보 가져오면 아래와 같은 정보를 줍니다. 
이 중 email을 회원가입때 필요한 username으로 사용하였습니다.
`/auth/google/signup`으로 쿠키에 googleUsername을 키로하여 이메일을 담고, 요청 body에 닉네임 정보를 담아 보내면 회원가입 완료
다음부터 구글 로그인 하면 JWT 발급됨
> [BE] 구글 로그인 구현

- packages/client/src/app/App.tsx
- packages/client/src/shared/apis/AxiosInterceptor.ts
- packages/client/src/shared/apis/index.ts
- packages/client/src/shared/apis/signUp.ts
- Axios Interceptor 추가
- then 또는 catch로 처리되기 전에 요청/응답을 가로챌 수 있습니다.
- 아래와 같은 경우에 유용합니다.
- 에러 핸들링
- 로딩 처리
- 헤더에 Authorization 미리 넣기
- 등등...
- postSignUp부분 api 추가
- 한 김에 api부분을 모두 처리하려 했으나...
- 제가 닉네임 부분 UI를 까먹은 것을 알게되어...... ....
- AxiosInterceptor 부분 코드 중 이상한게 있으면 코멘트주세용.
- 공통적으로 처리해야 할 로직이 있다면 저 코드에 추가해주시길바랍니다
닉네임 UI 추가할 생각하니 기쁨의눈물만나네요하하
> [FE] Axios Interceptor 추가

- packages/client/src/entities/posts/ui/Post.tsx
- packages/client/src/entities/posts/ui/Posts.tsx
- packages/client/src/features/controls/Controls.tsx
- packages/client/src/features/postModal/PostModal.tsx
- packages/client/src/features/writingModal/ui/WritingModal.tsx
- packages/client/src/pages/Home/index.tsx
- packages/client/src/shared/lib/types/post.ts
- packages/client/src/shared/store/usePostStore.ts
- packages/client/src/shared/store/useViewStore.ts
#42 
글 조회 모달 구현
캔버스에 모달을 띄울 수는 없어 데이터를 어떻게 모달창에 전달할까 하다가 간단하게 전역 스토어로 넣어주기로 결정했습니다.
usePostStore에 data로 글 조회 모달에 띄울 데이터를 관리합니다. 별을 클릭하여 글 조회 뷰로 넘어갈때 해당 별의 데이터를 store에 넣어주는 방식입니다.
Post의 props가 너무길어져서 별 관련 정보들은 data로 다 묶어줬습니다.
차후에 하단바에서 글 작성 버튼을 클릭해 글 쓰기 모달을 불러오는 과정을 구현할때는 useViewStore에서 view의 상태를 "WRITING"으로 변경해주면 글작성 모달이 나타납니다. 
https://github.com/boostcampwm2023/web16-B1G1/assets/35567292/480d34fb-2e5b-43e1-8b25-c6e8ad777561
차후에 이미지 캐러셀이나 슬라이드, 삭제 기능 구현이 필요합니다.
> [FE] 글 조회 모달 구현

- packages/client/src/pages/Landing/index.tsx
- packages/client/src/shared/apis/signUp.ts
- packages/client/src/shared/store/useSignUpStore.ts
- packages/client/src/shared/store/useToastStore.ts
- packages/client/src/widgets/nickNameSetModal/NickNameSetModal.tsx
- packages/client/src/widgets/nickNameSetModal/lib/constants.ts
- packages/client/src/widgets/nickNameSetModal/ui/NickNameInputContainer.tsx
- packages/client/src/widgets/signupModal/SignUpModal.tsx
- packages/client/src/widgets/signupModal/ui/IdInputContainer.tsx
#8 #9 #10 #11 #12 #13 #140 #15 
- pageReducer 변경
- 기존에는 prev와 next로밖에 움직일 수 없어서 set을 추가했습니다.
- 이렇게되니까 너무 복잡해지는 것 같은데 useNavigate를 사용하는 것도 고려해보면 좋을 것 같네요. 
- 현재 방식에서는 next 혹은 prev로 갈 때가 아니라면 페이지인덱스를 지정해줘야 하는데, 숫자로는 어떤 페이지인지 직관적으로 와닿지 않는 것 같습니다. 혹시 제가 pageReducer 사용법을 잘못 알고있다면 말해주세용. . 🥹
- @bananaba @MinboyKim 여기에 대해서 의견 남겨주시면 감사하겠습니다. 
- 회원가입 관련한 api 작업들 추가
- 좀 이상한 부분이 보인다면 코멘트주세요
- 회원가입모달에서 닉네임모달로 넘어갈 때 잠시 정보를 저장할 전역 store 추가
-  Toast 상태를 관리하기 위한 전역 store 추가
- text 부분이 비어있으면 뜨지 않고, 비어있지 않으면 띄우도록 했습니다. 
- 토스트를 사용할 때는 <Toast>를 직접 불러올 필요 없이  useToastStore 상태를 변경하면 됩니다.
- 닉네임모달 관련한 로직들 추가
- 회원가입모달에서 닉네임모달로 넘어갈 때 정보를 어떻게 저장할 것인가
- 로컬 스토리지를 사용하거나 Url에 붙여서 보내는 경우는 보안상 문제가 생길 수 있어서 코드 내에 보관하는 방법이 좋다고 생각했습니다.
- 닉네임 모달과 회원가입모달의 부모 컴포넌트가 없어서 전역 store를 사용하여 저장하고 있습니다. 
- 굳이 전역 store를 쓸 필요까지는 없을 것 같긴 …
> [FE] 회원가입 절차 구현

- packages/client/src/pages/Home/index.tsx
- packages/client/src/pages/Home/ui/UpperBar.tsx
- packages/client/src/pages/Home/ui/index.ts
- packages/client/src/shared/lib/constants/index.ts
- packages/client/src/shared/lib/constants/width.ts
- packages/client/src/shared/ui/search/Search.tsx
- packages/client/src/shared/ui/toast/Toast.tsx
- packages/client/src/shared/ui/underBar/UnderBar.tsx
- 하단바 컴포넌트 생성
- 피그마 디자인보다 전체적으로 더 작게 수정했습니다.
- 유저명은 임시로 넣어두었습니다.
- 상단바 추가
- Search 컴포넌트와 뒤로가기 버튼을 추가했습니다. 
- 화면의 상하 padding을 50px정도에서 30px로 수정했습니다.
- Toast의 위치도 같이 수정했습니다.
아는 디자이너분께 화면이 가로로 길어질 때 하단바도 같이 길어지는게 좋냐고 물어봤는데
사용자 관점에서 좌-우 시각범위가 길어지면 쉽게 피로감을 느낀다고 하네요
그래서 연두색 부분의 최대 width값은 1180px로 고정해두고,
화면이 더 작아졌을 때만 조금 더 줄어들도록 구현했습니다. 
원래는 연두색 부분 레이아웃을 따로 만들어두고, 
그 안에 하단바와 상단바를 추가하여
하단바 width를 100%로 주고 상단바는 justify-content: space-between으로 주려고 했습니다.
하지만 그렇게 하니 연두색 부분이 화면 전체를 덮어버려서 우주부분 컨트롤이 안되더라구영. .......
그래서 상단바와 하단바를 따로 두었습니다. 
뒤로가기 버튼과 검색바를 따로 두지 않고 상단바 안에 넣어버려서
상단바 부분 (뒤로가기 버튼과 검색바 사이 공간)은 마우스 컨트롤이 안되긴합니다. 
- style 부분
- media query 부분
Uploading 화면 기록 2023-11-26 오후 7.25.45.mov…
한 15분째 시도하고잇는데 영상이 참 안올라가네요 
그냥 사진으로 대체하겟습니다 ^^
- 창이 클 때
- 창이 작을 때
아직도 하단바가 좀 큰 느낌이 있긴한데..
다들어떻게생각하시나요
> [FE] 하단바, 상단바 UI 구현

- packages/client/src/app/Router.tsx
- packages/client/src/features/writingModal/ui/WritingModal.tsx
- packages/client/src/pages/Home/index.tsx
#86 
모달을 띄울 때 url도 변경해주는 것이 좋을 것 같아 방식을 조금 바꿔봤습니다.
Canvas를 그리는 Home 컴포넌트를 부모 라우트로 설정하고 하위 라우트에 모달들을 위치시킨 뒤 Home 컴포넌트에 하위 라우트인 모달들이 위치할 곳에 Outlet 컴포넌트를 두는 것으로 구현했습니다.
지금까지 진행한 부분들에 수정이 필요해보입니다.
매번 view state를 변경해야하는 이전 방식보다 좀 더 좋아진 방식이라는 생각이 듭니다.
> [FE] 라우팅 방식 설정

- packages/server/src/auth/auth.controller.ts
- packages/server/src/auth/auth.service.ts
- packages/server/src/auth/entities/user.entity.ts
- [16-01] 서버는 닉네임 데이터를 받아 유저를 조회한다. #187 
데이터베이스 nickname 컬럼 FULLTEXT 인덱싱
nickname 값을 받아 해당 nickname 값으로 시작하는 닉네임을 가진 유저들을 검색하는 Service 로직 구현
검색 API 구현
User Entity에 nickname컬럼 FULLTEXT 인덱싱을 위한 `@Index` 데코레이터 추가
MySQL의 전문검색과 AGINST 연산자에 쓰이는 모드들
서버가 실행되고 typeorm이 자동으로 `@Entity`가 붙은 엔티티들의 테이블을 갱신할때 사라지는 인덱스를 서버 실행시마다 생성해주는 방법
[개발 기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%A4%80%EC%84%AD%5D-1129(%EC%88%98)-%EA%B0%9C%EB%B0%9C-%EA%B8%B0%EB%A1%9D-%E2%80%90-NestJS---TypeORM%EC%9C%BC%EB%A1%9C-MySQL-%EC%A0%84%EB%AC%B8%EA%B2%80%EC%83%89-%EA%B5%AC%ED%98%84) 봐주시며 감사하겠습니다 ㅎㅎ
개발 기록 안에 학습 기록 링크도 있는데 나름 괜찮은 내용인 것 같아서 그것도 봐주시면 감사하겠습니다!
테스트용으로 데이터베이스에 저장한 유저 데이터들
Postman 테스트
```
localhost:3000/auth/search?nickname=테스트
```
결과가 잘 출력된 모습
> [BE] 닉네임 검색 API 구현

- packages/server/src/auth/auth.service.ts
- packages/server/src/auth/dto/signin-user.dto.ts
- packages/server/src/auth/enums/user.enum.ts
- 로그인시 아이디가 없으면 404 에러 상태코드 반환
- 비밀번호가 틀리면 401에러 상태코드 반환
존재하지 않는 아이디로 로그인 한 경우
비밀번호가 틀린 경우
> [BE] SignIn 에러 상태 코드 수정

- packages/server/src/board/board.service.ts
- packages/server/src/board/entities/image.entity.ts
- [08-10] 서버는 게시글 테이블(DB) 접근 시 필요하다면 트랜잭션을 적용한다. #112
- [08-09] 서버는 게시글 테이블(DB) 접근에 관한 에러를 처리한다. #111
개발기록 참고
이제 Image 삭제 및 새로 삽입하는 로직, 보드 수정 로직이 모두 하나의 트랜잭션에 들어간다. 성공!
- before
- after
이제 Image와 Board 레코드의 생성 로직이 모두 한 트랜잭션에 들어간다. 성공!
- 개발 기록
- [[재하] 1130(목) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%9E%AC%ED%95%98%5D-1130(%EB%AA%A9)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)
> [BE] PATCH /post/:id 트랜잭션 개선, POST /post 트랜잭션 적용

- packages/client/src/app/Router.tsx
- packages/client/src/features/postModal/index.ts
- packages/client/src/features/postModal/ui/ImageSlider.tsx
- packages/client/src/features/postModal/ui/PostModal.tsx
- packages/client/src/features/writingModal/api/sendPost.ts
- packages/client/src/features/writingModal/ui/WritingModal.tsx
- packages/client/src/shared/apis/AxiosInterceptor.ts
- packages/client/src/shared/store/useViewStore.ts
- packages/client/src/widgets/screen/index.tsx
#167 #192 
- 글 작성 요청 구현
우선은 별 데이터를 그냥 더미 데이터로 두고 진행했습니다. 후에 별 커스텀 데이터로 변경하고, 글 작성완료시 home 화면에서 데이터 refetching도 필요할 것으로 보입니다. 지금은 새로고침으로 테스트했습니다.
axios 인터셉터를 통해 글 작성 API 요청을 보내는 부분을 구현해줬습니다. CORS 에러가 또 나길래 인터셉터에도 `witCredentials true` 옵션을 추가해줬습니다.
글 모달에 스크롤바도 TextArea에서 구현한것과 동일하게 구현했습니다.
https://github.com/boostcampwm2023/web16-B1G1/assets/35567292/135fa7ea-08e8-4d46-9ef5-8eb20f2a8482
글 모달 스크롤바
잘되니까 기부니가 좋네요
글 작성 모달에 제목 Input도 하나 필요할 것 같습니다.
> [FE] 글 작성 요청, 글 모달 스크롤바 구현

- packages/client/src/features/postModal/ui/PostModal.tsx
- packages/client/src/features/writingModal/api/sendPost.ts
- packages/client/src/features/writingModal/ui/WritingModal.tsx
- packages/client/src/shared/ui/inputBar/InputBar.tsx
- packages/client/src/shared/ui/textArea/TextArea.tsx
- 글쓰기 모달에 제목 입력 input 구현
- 이미지 개수 0일때 "0" 문자열 출력하던 버그 수정
- 제목 및 내용 빈 값 입력시 발생하던 버그 수정
- 리로딩 임시구현
InputBar 컴포넌트 활용하여 제목 입력 input 구현해줬습니다.
---
원래는 `data.images.length > 0 && ... ` 이런식으로 구현되어있던 것을 위처럼 수정했었습니다. 문제는 저렇게 하니까 data.images.length가 0일때도 저 평가식이 참이 되더라구요? 😭 그래서 "0" 이라는 요상한 문자열이 출력되고 있었습니다. 그래서 그냥 이전처럼 `data.images.length > 0 && ... ` 방식으로 돌려놨습니다.
---
제목과 본문이 비어있을 때 서버에 요청하면 에러가 뜨는 버그를 발견했습니다. 비어있을 때 각각 "제목 없음", "내용 없음"을 기본값으로 서버에 전송하도록 해줬습니다.
---
글쓰기와 삭제시 임시로 그냥 리프레쉬 시키는 로직 넣어뒀습니다.
https://github.com/boostcampwm2023/web16-B1G1/assets/35567292/2128f8d9-ac8d-47fa-9c8b-4d8125f0f6f5
빈 제목 빈 내용으로 제출해도 글이 잘 작성되는 모습입니다. 위 영상을 보면 이미지가 없기 때문에 내용부분에 이상한 "0" 문자열이 보이는 것을 확인할 수 있습니다. 이젠 수정되었습니다 👍
> [FE] 글 제목 입력 기능, 몇가지 버그 수정

- packages/client/src/entities/posts/ui/Posts.tsx
- packages/client/src/pages/Home/ui/UpperBar.tsx
- packages/client/src/shared/apis/login.ts
- packages/client/src/shared/apis/star.ts
- packages/client/src/shared/store/useOwnerStore.ts
- packages/client/src/shared/ui/search/Search.tsx
- packages/client/src/shared/ui/underBar/UnderBar.tsx
- packages/client/src/widgets/loginModal/index.tsx
#64 #66 
- 로그인 시 유저의 닉네임을 쿠키에 저장하도록 함
- useOwnerStore에 pageOwnerNickName 추가
- 내 페이지가 아닐 경우, 다른 사용자의 닉네임을 저장함
- 내 페이지로 돌아왔을 때 자동으로 빈문자열이 됨
- 검색 후 이동하면 글 내용이 해당 닉네임을 가진 사용자의 글들로 바뀜
- 다른 사람 우주에서 뒤로가기 버튼을 누르면 다시 내 글들로 바뀜
- 검색바 추천닉네임에 본인 닉네임은 뜨지 않도록 했습니다.
- 우주 이동하는 부분을 어떻게 구현해야 할 지
- 그냥 글 내용만 바꾸도록 했는데 다른 좋은 방법이 있을까요? 
- 이후에 은하 바꾸는 기능도 넣게 되면.. 은하도 바꾸어야겠네요 
- 검색 후 우주 이동하는 부분
- 남의 우주에서 다시 내 우주로 돌아오는 부분
- 이동 전에는 별이 있는데 이동 후에는 별이 없는 모습을 보여주기 위한 영상입니다
- 계속 영상크기때문에 안올라가서 몇 번을 다시 녹화햇네요 흐흑 굉장히 다급하게 찍었습니다
https://github.com/boostcampwm2023/web16-B1G1/assets/80266418/e10b9c42-ccb1-4a4b-9029-3dee23759ab6
- 점점 정신이 혼미해지는 상태에서 작성한 코드입니다.. 고쳐야 할게 많을수도있겠어요 얼레벌레 코드 🧑🏿‍🎤 피알 내일 올리려다가 정신을 가다듬고 올리고 잡니다
- 이후 해야 할 것
- 검색했을 때 해당 닉네임이 존재하지 않으면 알럿창을 띄워야 합니다. 
- 우주 이동 시 글 정보와 하단바, 상단바만 바뀌고 있습니다.  카메라의 시점을 원래대로 돌려놓는다거나 하는 …
> [FE] 우주 검색 기능 구현

- packages/client/src/widgets/galaxyCustom/ui/SampleScreen.tsx
- packages/client/src/widgets/landingScreen/index.tsx
- packages/client/src/widgets/screen/index.tsx
- 우주 배경색 #070614로 변경
- Leva 컨트롤박스 디폴트로 접혀있게 설정
- Leva 초기 position 설정
Leva 컴포넌트를 활용해 디폴트 설정들을 처리해주었습니다.
Leva 컴포넌트, 우주 배경색
디폴트
open 시
> [FE] Leva 설정, 우주 배경색 변경

- packages/client/src/entities/posts/ui/Post.tsx
- packages/client/src/features/star/index.tsx
- 별의 라벨 디자인 변경
- 라벨에는 글의 제목이 뜹니다. 
- 하얀색이 촌스럽다는 익명의 백엔드1 의견과 border 색을 밝게 하면 좋겠다는 익명의 백엔드2 의견을 받아들였습니다. 🙏🏻
- 라벨의 width가 200px이 넘어가면 말줄임표로 마무리됩니다. (일단은 200px로 해놓았는데 이후 별의 크기를 보고 수정 예정입니다.)
- 폰트 크기같은 것들도 이후 별의 크기를 보고 변경할 예정입니다. 
- 별에 마우스 호버 시에만 라벨 보이도록 변경
- 카메라에 가까워졌을 때 라벨이 보이도록 할지, 마우스를 호버했을 때 라벨이 보이도록 할지 고민했지만
- 다수결의 법칙에 따라 호버 방식을 선택했읍니다. 🥹 
- 이후에 카메라 기준으로 일정 범위 내에 존재하는 별들만 호버 시에 라벨이 보이도록 변경하면 좋을 것 같네요.
- 이 과정에서 Star의 props로 onPointerOver, onPointerOut를 추가했습니다. 
- 어떻게 별의 윗부분으로 라벨을 올릴지
- 일단 퍼센트로 조절해서 하긴 했는데, 별 크기가 달라져도 그대로 유지될지는 잘 모르겠습니다.
- 이후 별을 실제로 생성해보고 변경할 수도 있을 것 같네요.
- theme를 불러올 때 에러 발생
- 왠지 모르겠는데 여기서만 에러가 발생하더라고요.. 
- 프론트분들이 함께 있었으니 에러 메시지는 따로 첨부하지 않겠습니다 🕺🏼
- 그래서 일단 theme를 직접 import해서 사용하고 있습니다.   
라벨 디자인 부분
- 뭔가.....묘하게 불안정해보이네요....왜일까,,. …
> [FE] 별 라벨 디자인 변경

- packages/server/src/auth/auth.controller.ts
- packages/server/src/auth/auth.service.ts
- packages/server/src/auth/decorators/swagger/get-username-by-sharelink.decorator.ts
- packages/server/src/exception-filter/http.exception-filter.ts
- packages/server/src/main.ts
HttpExceptionFilter 추가
main.ts에 useGlobalFilter로 전역에 HttpExceptionFilter 적용
HttpException이 발생하면 에러 로그를 logs/exceptions/{날짜}.log 파일로 저장하도록 구현
check-signin api에서 데이터베이스를 조회해 현재 user status 정보도 반환 데이터에 포함되도록 수정
에러를 발생시키면
에러 로그가 남고
packages/server/logs 폴더에 로그가 쌓임
> [BE] Exception Filter 구현 및 check-signin api 수정

- .github/workflows/deploy.yml
- .gitignore
- Dockerfile-web
- nginx.conf
- packages/admin/.gitignore
- packages/admin/index.html
- packages/admin/src/App.tsx
- packages/admin/src/components/Nav.tsx
Dockerfile-Web에 admin dist폴더 전송 명령어 추가
GitHub Actions deploy.yml에 admin build 과정 추가
일단 /admin/index.html로 들어가면 제대로 실행되는 거 확인했습니다 ㅎㅎ
화면에 zz는 아래에 이유가 나옵니다.
근데 yarn workspace admin build하면 다음과 같이 저희가 작성한 코드는 빌드가 안되네요..
zz는 제가 그냥 테스트용으로 추가해놓은 겁니다!
---
- css, js 찾지 못한 문제 해결
/admin/assets/~~.js 이런 식으로 파일을 찾아와야 하는데, 그냥 /assets/~~.js 이런 식으로 찾아서 NotFound 에러가 발생
아래와 같이 nginx.conf를 수정하여 해결
```
location ~* \.(?:css|js)$ {
try_files $uri /admin$uri =404;
expires 1y;
access_log off;
add_header Cache-Control "public";
}
```
그냥 $uri(/assets/~~.js)로 못찾으면 /admin$uri(/admin/~~.js)로 찾음 -> 그래도 없으면 404
- 페이지 라우팅이 admin이 아닌 client로 가는 문제 해결
현재 테스트로 해놓은 Nav바에서 라우팅이 /, /about, /abc 이런 식으로 하다보니 링크 클릭을 하면 admin 페이지 내가 아닌 클라이언트 라우팅으로 감
Nav바 링크를 /admin, /admin/about, /admin/abc 이런 식으로 수정
```typescript
// nav바 컴포넌트 …
```
> [BE] admin 배포용 Dockerfile-Web 수정, cicd 수정

- packages/client/src/entities/posts/ui/Post.tsx
- packages/client/src/features/postModal/ui/ImageSlider.tsx
- packages/client/src/features/postModal/ui/PostModal.tsx
- packages/client/src/shared/ui/textArea/TextArea.tsx
- packages/client/src/widgets/screen/index.tsx
- 글 수정 기능 구현
- Leva 컨트롤박스 메인화면에서만 보이도록 수정
- 게시글에서 이미지 크기 조정
isEdit state를 활용해 현재 수정중인지 판단합니다. 수정하기 버튼을 통해 수정상태로 진입하면 writingModal에서 구현했던것과 비슷하게 InputBar와 TextArea 컴포넌트를 활용해 수정할 내용들을 입력받고 서버로 전송하는 로직입니다.
기존의 데이터를 InputBar와 TextArea에 전달하기 위해 useEffect훅을 사용해줬습니다.
유저의 입력을 content state로 업데이트하는 부분에서, 계속해서 마지막 글자가 짤리는 현상이 발생했는데, [#128 ](https://github.com/boostcampwm2023/web16-B1G1/pull/128#discussion_r1401658180)에서 @KimGaeun0806 님이 지적해주신 부분때문이었습니다 ㅎㅎ 바로 생각나서 금방 고칠 수 있었습니다 감사해요 👍
PostModal.tsx
https://github.com/boostcampwm2023/web16-B1G1/assets/35567292/9de2dd49-3513-4217-a1e4-d61acb36cee9
PostModal이 너무 길어져서 좀 분리가 필요해보이긴합니다
> [FE] 글 수정 기능 구현

- packages/server/src/auth/auth.service.ts
- packages/server/src/auth/decorators/swagger/get-share-link-swagger.decorator.ts
- packages/server/src/auth/decorators/swagger/get-username-by-sharelink.decorator.ts
- packages/server/src/auth/entities/user.entity.ts
- packages/server/src/auth/enums/user.enum.ts
- packages/server/src/auth/pipes/StatusValidationPipe.ts
user.status가 private이어도 상관 없이 링크를 조회하도록 수정
status 기본값 public으로 변경
only_link 상태 삭제
StatusValidationPipe 수정
Swagger 수정
status가 public인 유저만 검색되도록 수정
검색 응답
유저 상태를 public으로 변경
검색 결과에 새로 포함된 모습
> [BE] sharelink, search api 수정

- packages/server/src/auth/auth.service.ts
- OAuth2.0을 통한 회원가입 시 galaxy record가 생성되지 않는 문제 버그 픽스
- signUpwithOAuth 메소드에도 해당 로직 추가
> [BE] OAuth2.0 통한 회원가입 시 Galaxy Record 생성

- packages/client/src/pages/Home/index.tsx
- packages/client/src/shared/apis/galaxy.ts
- packages/client/src/shared/apis/index.ts
- packages/client/src/shared/store/useCustomStore.ts
- packages/client/src/shared/store/useGalaxyStore.ts
- packages/client/src/widgets/galaxy/lib/modules/instances.tsx
- packages/client/src/widgets/galaxy/lib/modules/positions.ts
- packages/client/src/widgets/galaxyCustom/index.tsx
- packages/client/src/widgets/galaxyCustom/ui/LeftButton.tsx
- packages/client/src/widgets/galaxyCustom/ui/Sliders.tsx
- packages/client/src/widgets/galaxyCustom/ui/TopButton.tsx
- 은하 커스텀의 실시간 보기 기능을 활성화 했다
이 문제를 어떻게 해결해야 하나
왜 안되는지 이해가 가지 않는 문제라 해결책을 찾는것 자체가 문제였다
멋진 커스텀 화면
https://github.com/boostcampwm2023/web16-B1G1/assets/78800560/4d778ae5-73e3-4ecf-91f8-047c3485469a
> [FE] 은하 커스텀 화면

- packages/server/src/board/board.controller.ts
- packages/server/src/board/board.service.ts
- packages/server/src/board/entities/board.entity.ts
- packages/server/src/sentiment/sentiment.service.ts
- packages/server/test/board/board.e2e-spec.ts
- packages/server/test/sentiment/sentiment.e2e-spec.ts
- async/await가 제대로 적용되지 않은 비동기 로직들로 인해 테스트 시 어떨 때는 통과되고, 어떨 때는 통과가 되지 않는 문제들이 발생함
- 컨트롤러 단의 필요한 메소드를 async로, service를 await해줌으로써 response 후 결과가 반영되는 문제 해결
- transaction interceptor의 commitTransaction()이 response 후에 적용되는 문제(POST /post 등)는 아직 해결 못함 
- 개발 기록
- [[재하] 1207(목) 개발기록](https://github.com/boostcampwm2023/web16-B1G1/wiki/%5B%EC%9E%AC%ED%95%98%5D-1207(%EB%AA%A9)-%EA%B0%9C%EB%B0%9C%EA%B8%B0%EB%A1%9D)
> [BE] sentiment, board 모듈 e2e 테스트 코드 작성, 테스트, 코드 개선

- packages/server/test/galaxy/galaxy.service.spec.ts
- packages/server/test/sentiment/sentiment.service.spec.ts
- 코드 커버리지를 100%로 만들기 위해 모든 에러처리를 통과하는 유닛 테스트 코드를 작성함
> [BE] galaxy, sentiment 서비스 유닛 테스트

- packages/client/src/entities/posts/ui/Post.tsx
- packages/client/src/features/postModal/ui/PostModal.tsx
- 이전에 다른 사람의 은하에서 별을 클릭 시/ /home으로 돌아오던 에러 해결
- nivagate('home' ~~ ) 으로 되어있어서 발생한 에러였습니다.  
- 자꾸 이상하게 되길래 좀 헤맸는데 알고보니 모달의 뒤로가기 버튼에도 적용되어있어서 그랬던거였네요..
- path 부분
https://github.com/boostcampwm2023/web16-B1G1/assets/80266418/dd071b37-2b21-4a7c-ab84-163ad694115c
- 테스트해보시고 문제있으면 이야기해주세요.
> [FE] 다른 사람 은하에서 별 클릭했을 때 home으로 돌아가는 에러 해결

- packages/client/src/entities/posts/ui/Posts.tsx
- packages/client/src/shared/lib/constants/width.ts
- packages/client/src/shared/routes/PrivateRoute.tsx
- packages/client/src/shared/routes/PublicRoute.tsx
- packages/client/src/widgets/underBar/UnderBar.tsx
- 별 스킨 만들기 버튼을 삭제했습니다.
- 동민님 코드랑 꼬일 것 같아서 코드 주석처리 해두었습니다.
- 남의 은하에 갔을 때 기존에는 버튼이 비활성화되었었는데, 아예 보이지 않도록 수정했습니다.   
- 남의 은하에 가면 로그아웃 버튼만 보입니다.
- 반응형 width값을 변경했습니다.
- 버튼이 하나 없어져서, 하단바가 최대로 줄어들 수 있는 width값을 수정했습니다 . 
- Posts.tsx에서 api 호출하는 부분 수정
```js
if (!page) return; // 추가된 코드
if (page === 'home') {
내 우주일 때 api 통신 코드 
return;
}
남의 우주일 때 api 통신 코드 
```
- Posts.tsx에서, page가 home임에도 불구하고 자꾸 home이 아닐 때 호출되어야 하는 함수가 호출되었습니다.
- 그래서 star/by-author api가 계속 호출되어 에러가 나고 있었습니다.
- 알고보니 page 변수가 불러와지기 전 page가 빈 값일 때, '남의 우주일 때 api 통신 코드'가 먼저 실행되는 것이었습니다. 
```js
if (page === 'home') {
내 우주일 때 api 통신 코드 
return;
}
남의 우주일 때 api 통신 코드 
```
- 그래서 가장 앞에 page가 falsy한 값이라면 리턴되게 처리해주었습니다.
- Underbar.tsx
https://github.com/boostcampwm2023/web16-B1G1/assets/80266418/c200e5aa-6190-4911-8f63-e19bdf3ad9f5
> [FE] 하단바 디자인 수정

- packages/server/src/auth/auth.controller.ts
- packages/server/src/auth/auth.service.ts
- packages/server/src/auth/decorators/swagger/check-nickname-swagger.decorator.ts
- packages/server/test/auth/auth.controller.spec.ts
- packages/server/test/auth/auth.e2e-spec.ts
AuthController 유닛 테스트 작성
닉네임을 쿼리스트링으로 받아 닉네임을 가진 회원이 있으면 true, 없으면 404를 발생시키는 API 구현
필요한 함수를 jest.fn()으로 만들고 함수.mock.calls를 하면 아래와 같이 확인할 수 있네요 !
@Res로 리스폰스를 가져와서 쿠키 처리하는 부분 어떻게 테스트해야 하나 했는데 아래처럼 해결했습니다.
```
const response = { cookie: jest.fn() } as any; // res의 cookie 메서드를 mock으로 만들어줌
// response의 cookie 메소드의 호출 테스트
expect(response.cookie.mock.calls[0][0]).toBe('accessToken'); // 첫 번째 호출의 첫 번째 인자가 'accessToken'인지 확인
expect(response.cookie.mock.calls[0][1]).toBe('token'); // 첫 번째 호출의 두 번째 인자가 'token'인지 확인
expect(response.cookie.mock.calls[0][2]).toBeDefined(); // 첫 번째 호출의 세 번째 인자가 정의되어 있는지 확인
expect(response.cookie.mock.calls[1][0]).toBe('refreshToken');
expect(response.cookie.mock.calls[1][1]).toBe('token');
expect(response.cookie.mock.calls[1][2]).toBeDefined();
```
테스트 코드 통과 …
> [BE] Auth Controller 유닛 테스트 작성, checkNickname Api 구현

- packages/admin/src/App.tsx
- packages/admin/src/components/Board/Board.tsx
- packages/admin/src/components/ExceptionStatistics/ExceptionStatistics.tsx
- packages/admin/src/components/Login/Login.tsx
- packages/admin/src/components/SystemInfo/SystemInfo.tsx
- packages/server/src/admin/admin.controller.ts
- packages/server/src/admin/admin.module.ts
- packages/server/src/admin/admin.service.ts
- packages/server/src/admin/jwt.strategy.ts
- (BE) 어드민 모듈 signin, signout API 구현
- (FE) 어드민 로그인 페이지 구현, 비인가 접근시 리다이렉트
https://github.com/boostcampwm2023/web16-B1G1/assets/138586629/27fe0088-e265-42d0-9f88-b8cc6decc656
https://github.com/boostcampwm2023/web16-B1G1/assets/138586629/475fb5d6-2b5a-4941-9c3b-20b4d52cafd0
> [BE] 어드민 페이지 계정인증 구현

- packages/server/src/board/board.controller.ts
> [HotFix] 사진 업로드 개수 제한 변경

- .github/workflows/deploy.yml
- checksum 매치 오류를 해결하기 위해 yarn install 전 캐시 지우기
> [HotFix] checksum 매치 오류를 해결하기 위해 yarn install 전 캐시 지우기

- packages/client/src/widgets/galaxy/lib/constants/index.ts
- packages/client/src/widgets/warpScreen/lib/constants.ts
- packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
- Galaxy 별 색을 변경했습니다.
- 최적화 한 후에 색이 너무 진해진 것 같아서 더 연하게 하려 했으나... 그냥.. 네 뭐 결과적으로는 별 차이가 없는 것 같기도 하네요
- Space Warp 라인 색을 변경했습니다.
- 기존에는 알록달록한 느낌이었는데 저희 UI 컨셉에 맞추어 보랏빛으로 변경했습니다.  
- 무슨 색을 할 지...
- 그냥 색만 봐주시면 될 것 같네요
https://github.com/boostcampwm2023/web16-B1G1/assets/80266418/c9e24231-c8f1-43a2-bc65-596779fe18d1
> [FE] Galaxy, WarpScreen 색상 변경

- packages/client/index.html
- packages/client/src/pages/Home/Home.tsx
- packages/client/src/shared/lib/constants/error.ts
- 전체화면 오류 수정 
- 감정 분석 에러 처리
- 구글 애널리틱스 스크립트 추가
모달 포탈의 루트가 FullScreen 컴포넌트의 밖에 있어서 전체화면시 모든 모달이 보이지 않는 버그가 발생했습니다. 어쩔 수 없이 모달 포탈의 루트를 Home 컴포넌트로 이동시켰습니다.
감정분석 에러 출력
전체화면 모달 출력
> [FE] 전체화면 오류 수정, 감정 분석 에러 처리, 구글 애널리틱스

- packages/server/src/app.module.ts
- packages/server/src/main.ts
nginx 리버스 프록시로 동작하는 배포 상태라 request ip가 모두 web컨테이너 내부ip로 찍힘
throttler가 ip기반으로 정상 동작하기 위해, X-Forwarded-For에 있는 최종 ip를 전달해줘야 함
'trust proxy'를 1로 설정해 이를 해결
1. [throttler와 reverse proxy](https://trend21c.tistory.com/2295)
2. [NestJS에서 app.set() 적용법](https://github.com/nestjs/nest/issues/2293#issuecomment-500020645)
3. [NestJS Rate Limit 공식문서](https://docs.nestjs.com/security/rate-limiting)
> [BE] trust proxy 설정 (원본 ip 반환하여 throttler 문제 해결)

- packages/client/src/entities/posts/ui/Post.tsx
- packages/client/src/entities/posts/ui/Posts.tsx
- packages/client/src/widgets/starCustomModal/lib/generateStarPosition.ts
- 별의 위치가 사각형 내부에서 생성되던 문제를 해결해 원형으로 생성되도록 했다
- 별 생성 삭제 애니메이션을 만들었다
useFrame 안에서 setState를 가능한 안하려고 했는데 ref로 참조할수 없는 수치는 이렇다할 방법이 없는것 같더라구요
https://github.com/boostcampwm2023/web16-B1G1/assets/78800560/c227103d-f6f6-42c4-8035-3ecf3a930cb9
https://github.com/boostcampwm2023/web16-B1G1/assets/78800560/576c2039-810e-4a26-a7e0-a9044c284ae4
> [FE] 별 생성 위치 조정, 별 생성 삭제 애니메이션

- packages/server/src/admin/admin.service.ts
- packages/server/src/board/dto/create-board.dto.ts
- packages/server/src/board/file.service.ts
- packages/server/src/interceptor/transaction.interceptor.ts
- packages/server/src/star/dto/update-star.dto.ts
- 별글 생성, 수정 시 제목 20자 제한
- 이미지 업로드 시 파일 확장자 png, jpg, jpeg로 제한, sharp 에러 처리
- 의미없는 Import 제거
DB 엔티티쪽도 변경해줄 수 있지만 기존 레코드로 인해 DB 에러가 발생할 수 있으므로 엔드포인트 검증만 개선했습니다.
> [BE] 리팩토링, 에러 처리 개선

- packages/client/src/pages/Home/Home.tsx
- packages/client/src/widgets/warpScreen/WarpScreen.tsx
- packages/client/src/widgets/warpScreen/ui/SpaceWarp.tsx
- FadeoutScreen에 onAnimationEnd를 추가하여, animation이 끝나면 isSwitching이 'end'가 되도록 했습니다.
- isSwitching === 'end'일 경우 WarpScreen에서 null을 리턴하도록 했습니다.
- geSpaceWarpLinesInfo 함수를 geTSpaceWarpLinesInfo로 수정했습니다. 
- isSwitching이 'end'일 경우를 어디에서 처리할지
- 개인적으로 컴포넌트 내에서 null을 리턴하는 것이 더 깔끔하다고 생각해서 그렇게 처리했습니다. 
- WarpScreen
> [FE] WarpScreen FadeoutScreen에 onAnimationEnd 추가

- packages/client/src/shared/lib/types/post.ts
- packages/client/src/widgets/postModal/ui/PostModal.tsx
- packages/client/src/widgets/writingModal/ui/WritingModal.tsx
- 글 수정 시 제목과 본문이 비어있어도 걸러지지 않던 부분을 제한해줬습니다.
- 공백 이슈가 좀 있었네요. 잘 처리되어서 다행입니다 🐧
> [FE] 글 수정 제목 및 본문 제한
